# Generated by Django 2.2.10 on 2021-12-21 06:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=50, verbose_name='Текст варианта ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_survey', models.CharField(max_length=40, verbose_name='Название')),
                ('date_to_start', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 6, 14, 52, 53612, tzinfo=utc), verbose_name='Дата старта')),
                ('date_to_finish', models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 14, 52, 53628, tzinfo=utc), verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('type_question', models.CharField(choices=[('TR', 'текстовый ответ'), ('SC', 'один ответ'), ('MC', 'несколько ответов')], default='TR', max_length=2, verbose_name='Тип вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Survey', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=50, verbose_name='Текст ответа')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveyapp.AnswerQuestion', verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
